//Keyboard events and key properties
/* Keyboard events are only generated by <input>, <textarea>, <summary>
     and anything with the contentEditable or tabindex attribute.  */
const itemInput = document.getElementById("item-input");

const onKeyPress = (e) => {
  console.log("keypress");
};

const onKeyUp = (e) => {
  console.log("keyup");
};
const onKeyDown = (e) => {
  //console.log(e.code);
  //document.querySelector("h1").innerHTML = e.key;
  if (e.key === "Enter") {
    alert("you pressed enter");
  }
  //Keycode
  if (e.keyCode === 53) {
    alert("you pressed 5");
  }
  //Code
  if (e.code === "KeyD") {
    alert("you pressed D");
  }
  if (e.repeat) {
    //console.log("You are holding down " + e.key);
  }
  console.log("Sihft: " + e.shiftKey);
  console.log("Ctrl: " + e.ctrlKey);
  console.log("Alt: " + e.altKey);
  if (e.shiftKey && e.key === "K") {
    alert("You pressed shift + K");
  }
};
//input of any key adds represents as keypress, keypress is not recommended anymore
//itemInput.addEventListener("keypress", onKeyPress);

//The keyup event - is fired when a key is released.
//itemInput.addEventListener("keyup", onKeyUp);

/* The keydown event -  is fired when a key is pressed.
Unlike the deprecated keypress event, the keydown event
 is fired for all keys, regardless of whether they produce a character value. */
itemInput.addEventListener("keydown", onKeyDown);
